name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
      - name: Run a multi-line script
        run: |
          sudo apt-get install -y aria2
          aria2c -s8 -x8 http://speedtest.tele2.net/1GB.zip
          mv 1GB.zip 1GB.bin
          echo test, and deploy your project.
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: 1GB.bin
          draft: true
          name: release_${{ steps.date.outputs.date }}
          tag_name: tag_${{ steps.date.outputs.date }}
      - name: Release-Output
        run: |
          echo ${{ steps.Release.outputs.id }}
