name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
      - name: Run a multi-line script
        run: |
          sudo apt-get install -y aria2
          aria2c -s8 -x8 http://speedtest.tele2.net/10GB.zip
          mv 10GB.zip 10GB.bin
          echo test, and deploy your project.
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: release2536457867
        uses: ncipollo/release-action@v1
        with:
          artifacts: 10GB.bin
          bodyFile: "Release.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          name: release_${{ steps.date.outputs.date }}
          tag: tag_${{ steps.date.outputs.date }}
      - name: Release-Output
        run: |
          echo ${{ steps.release2536457867.outputs }}
